openapi: 3.0.0
#-----
info:
  title: Calculadora
  description: calculadora
  version: 1.0.0
  termsOfService: 'http://swagger.io/terms/'
  #-----
  contact:
    email: otabora@outlook.es
  #-----
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  #-----
servers:
  # Vert.X
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Sifponia/UsuaioApi/1.0.0
  - description: Vertx
    url: http://localhost:9090/calculadora
  #-----
tags:
  - name: Calculadora
    description: Calculadora
  #-----
paths:
  '/addall':
    get:
      summary: Lista de calculos
      operationId: addList
      tags:
        - Calculadora
      responses:
        '200':
          description: Permitir listar el histórico de forma paginada
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calculadora'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Sever Error

  '/add':
    post:
      summary: Recibe dos entradas un numero (x) y (y)
      operationId: add
      tags:
        - Calculadora
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resultado'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calculadora'

        '404':
          description: Failed. Request not found
        '405':
          description: Failed. Method Not Allowed

  '/resta':
    post:
      summary: recibe dos dos entradas un numero (x) y (y)
      operationId: restaId
      parameters:
        - in: query
          name: x
          description: number
          required: true
          schema:
            type: number
        - in: query
          name: y
          description: x
          required: true
          schema:
            type: number
      tags:
        - Calculadora
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Calculadora'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calculadora'
        '404':
          description: Failed. Request not found
        '405':
          description: Failed. Method Not Allowed

  '/addall/{id}':
    get:
      summary: Permitir obtener histórico por ID
      operationId: findByIdSuma
      parameters:
        - name: id
          in: path
          required: true
          example: 1
          description: Recupera un ID de la operacion
          schema:
            type: number
      tags:
        - Calculadora
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calculadora'
        '404':
          description: Failed. Request not found
        '405':
          description: Failed. Method Not Allowed
components:
  schemas:
    Calculadora:
      type: object
      required:
        - x
        - y
      properties:
        id:
          type: integer
          format: int64
          description: Id de identificación
          example: 1
        x:
          type: number
          description: Recibe un primer numero
          example: 1.50

        y:
          type: number
          description: Recibe un segundo numero
          example: 1
        operacion:
          type: number
          description: Recibe el tipo de operacion
          example: +
        result:
          type: number
          description: Guarda el resultado de la operacion
          example: 2.50
    Resultado:
      type: object
      properties:
        result:
          type: number
      example: 2.50

