openapi: 3.0.0
#-----
info:
  title: Calculadora
  description: calculadora
  version: 1.0.0
  termsOfService: 'http://swagger.io/terms/'
  #-----
  contact:
    email: otabora@outlook.es
  #-----
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  #-----
servers:
  # Vert.X
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Sifponia/UsuaioApi/1.0.0
  - description: Vertx
    url: http://localhost:9090/calculadora
  #-----
tags:
  - name: calculadora
    description: Devuelve todos los valores de las operaciones de la
      calculadora 
  #-----
paths:
  /calculadora:
    get:
      summary: Lista de operaciones aritmeticas
      operationId: listaCalculadora
      tags:
        - calculadora
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: An paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calculadora'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Recibe dos valores para realizar un operacion         aritmetica.
      operationId: crearCalculadora
      tags:
        - calculadora
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Calculadora'
      responses:
        '200':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /calculadora/{id}:
    get:
      summary: Devuelve una operacion de la BBDD
      operationId: mostrarPorId
      tags:
        - calculadora
      parameters:
        - name: id
          in: path
          required: true
          description: La identificaci贸n de la operacion a recuperar.
          schema:
            type: number
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calculadora'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /calculadora/{DeleteId}:
    delete:
      summary: Borra una operacion de la calculadora
      operationId: borrarPorId
      tags:
        - calculadora
      parameters:
        - name: DeleteId
          in: path
          required: true
          description: La identificaci贸n de la operacion a recuperar.
          schema:
            type: number
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calculadora'
components:
  schemas:
    Calculadora:
      type: object
      required:
        - numeroOne
        - numerTwo
      properties:
        id:
          type: integer
          format: int64
          description: Id de identificaci贸n
        numeroOne:
          type: number
          description: Recibe un primer numero
        numerTwo:
          type: number
          description: Recibe un segundo numero
        result:
          type: number
          description: Guarda el resultado de la operacion
        context:
          type: object
          description: Guarda es esquema de la documentaci贸n de la Ap
    Error:
      type: object
      required:
        - id
        - result
      properties:
        id:
          type: integer
          format: int32
        result:
          type: number
